name: Build and Release
# If Action doesn't run, check: https://www.githubstatus.com/
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Build for Ubuntu
        run: GOOS=linux go build -o sys-echo-linux main.go
      
      - name: Build for Mac Darwin
        run: GOOS=darwin go build -o sys-echo-darwin main.go

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.sha }}"
          release_name: Release v${{ github.sha.slice(0,5) }}
          body: |
            Changes in this release:
            ${{ join(github.event.commits.*.message, '\n- ') }}
          draft: false
          prerelease: false
      # - name: Build Docker Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     dockerfile: Dockerfile
      #     push: true
      #     tags: danfedick/sys-echo:latest
      

      
      # - name: Upload Ubuntu Docker Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: danfedick/sys-echo:${{ github.sha | truncate(7, '') }}
      
      # - name: Logout from Docker
      #   run: docker logout
      
      # - name: Login to Docker
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      