name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build for Ubuntu
        run: GOOS=linux go build -o sys-echo-linux main.go
      
      - name: Build for Mac Darwin
        run: GOOS=darwin go build -o sys-echo-darwin main.go

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: danfedick/sys-echo:latest
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release v${{ github.ref }}
          body: |
            Changes in this release:
            ${{ join(github.event.commits.*.message, '\n- ') }}
          draft: false
          prerelease: false
      
      - name: Upload Ubuntu Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: danfedick/sys-echo:${{ github.ref }}
      
      - name: Logout from Docker
        run: docker logout
      
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      