name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build Ubuntu binary
      run: go build -o sys-echo main.go

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          Changelog:
          - New version of reslease action
        draft: false
        prerelease: false

    - name: Upload Ubuntu binary
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sys-echo
        asset_name: sys-echo-ubuntu-x86-64
        asset_content_type: application/octet-stream

    - name: Build Mac binary
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -o sys-echo-darwin-x86_64

    - name: Upload Mac binary
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sys-echo
        asset_name: sys-echo-darwin-x86-64
        asset_content_type: application/octet-stream
